version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app:rw
    env_file:
      - .env
    command: "flask run -h 0.0.0.0 -p 5000"
    depends_on:
      - redis

  redis:
    container_name: redis-db
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data:rw
    