version: '3'

services:
  app:
    container_name: app
    build: .
    image: /app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app:rw
    env_file:
      - .env
    command: "flask run -h 0.0.0.0 -p 5000" 